services:
  postgres:
    container_name: "snaily-cad-postgres"
    image: postgres:latest
    environment:
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - cad_web
    volumes:
      - ./.data:/var/lib/postgresql
    restart: unless-stopped

  api:
    container_name: "snaily-cad-api"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      CORS_ORIGIN_URL: ${CORS_ORIGIN_URL}
    ports:
      - "${PORT_API}:${PORT_API}"
    expose:
      - ${PORT_API}
    depends_on:
      - postgres
    networks:
      - cad_web
    restart: always
    volumes:
      - ./apps/api/public:/snailycad/apps/api/public

  client:
    container_name: "snaily-cad-client"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: client
    environment:
      NEXT_PUBLIC_CLIENT_URL: ${CORS_ORIGIN_URL}
      NEXT_PUBLIC_PROD_ORIGIN: ${NEXT_PUBLIC_PROD_ORIGIN}
      DOMAIN: ${DOMAIN}
    ports:
      - "${PORT_CLIENT}:${PORT_CLIENT}"
    expose:
      - ${PORT_CLIENT}
    depends_on:
      - postgres
    networks:
      - cad_web
    restart: always

networks:
  cad_web:
    {}
